name: Build and Deploy to Azure

on:
  push:
    branches:
      - master  # or your deploy branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # match your GitHub environment name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_DEPLOY_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: franjefriten/streamlit_app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: accap
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          configuration-file: compose.yaml  # Path to your compose file
