name: Deploy Multi-container App to Azure Web App

env:
  AZURE_WEBAPP_NAME: accap
  STREAMLIT_IMAGE: franjefriten/streamlit_app:latest  # Your private Docker Hub image
  POSTGRES_IMAGE: postgres:latest                    # Public Docker Hub image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub (for your private Streamlit image)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_DEPLOY_TOKEN }}      # Docker Hub access token

      - name: Deploy multi-container to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            ${{ env.STREAMLIT_IMAGE }}
            ${{ env.POSTGRES_IMAGE }}
          configuration-file: compose.yaml